repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: tflint
  - id: gofmt
- repo: https://github.com/Bahjat/pre-commit-golang
  rev: master
  hooks:
  - id: go-fmt-import
  - id: go-vet
  - id: go-static-check # install https://staticcheck.io/docs/
  - id: golangci-lint # requires github.com/golangci/golangci-lint
