repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: terragrunt-hclfmt
  - id: yapf
  - id: tflint
  - id: shellcheck
  - id: gofmt
  - id: golint